### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by qwertyatp** [MILVLG/openvqa#36]
Hello, 

I have experienced some issues when getting openvqa to set up. First, the "setup.sh" file is not available in this repository, so I just used the "setup.sh" file in the mcan-vqa repository. Is this suitable?

This may be related to the first issue, but when I try the first run command "python3 run.py --RUN='train' --MODEL='mcan_small' --DATASET='vqa'", I receive the error "./data/vqa/feats/train2014 NOT EXIST". 

Thank you very much for your help.

**Comment by MIL-VLG** [comment]
The setup has some error in the setup part, as the folder name for openvqa is slightly different from mcan-vqa. Will will fix it soon.
You can manually put the unzipped feature folders (i.e., the train2014, val2014, test2015 folders) into the `data/vqa/feats` folder and all the json files into `data/vqa/raw` folder, respectively.

**Comment by MIL-VLG** [comment]
we have fixed and updated the VQA setup for openvqa in INSTALL.md.
