### ISSUE TITLE
Downloading mscoco bottom-up features

### ISSUE THREAD

**Issue by mrfarazi** [MILVLG/openvqa#45]
Hello,
While downloading the bottom-up features for the mscoco images, either from OneDrive or BaiduYun, the download fails after a few minutes. I have tried several times from different browsers and OS, but it didn't work.
Could you please give direct links to the files so that one can 'wget' or provide a script to download them.

Thanks in advance

**Comment by yuzcccc** [comment]
Sorry that we still do not have such any better choice than OneDrive or BaiduYun. If you have configured the environment for caffe. You can follow the script at the bottom of this project to extract the features for the images for VQA-v2 by yourself.

**Comment by mrfarazi** [comment]
Thanks for your reply. 
On the OneDrive website it says,
"Downloads are subject to the following limits: individual file size limit: 10GB; total zip file size limit: 20GB; total number of files limit: 10,000." I guess this was the cause of the error.

If anyone has any better idea, or any workaround, please let me know.

**Comment by MIL-VLG** [comment]
emm, it is strange. I have asked someone else to use the OneDrive link, they can successfully download the file without such limitations.

**Comment by shahansa** [comment]
Adding a late comment in case someone needs this in the future. 
I faced similar problem with the download but found a workaround. wget can resume from where the download is failed. To use wget with onedrive link given, observe the POST request in developer tab and copy the request header. Now construct a wget command with all of the header data including the cookies to download the files.
