### ISSUE TITLE
Setup Issues #2

### ISSUE THREAD

**Issue by HyperDenton** [MILVLG/openvqa#46]
Hi, 

I tried setting up the environment described in the [doc](https://openvqa.readthedocs.io/en/latest/basic/install.html) and then ran

 `python3 run.py --RUN='train' --MODEL='mcan_small' --DATASET='vqa'` 

in the directory, but I didn't receive any output or error message,let alone any checkpoint files or training log. 

I also tried running other codes such as

 `python3 run.py --RUN='train' --MODEL='mcan_large' --DATASET='vqa'` 

and it still showed nothing.

What could be the problem?

Thank you.

**Comment by HyperDenton** [comment]
Sorry, my mistake. It's because my anaconda is misconfigured. When I ran
`python run.py --RUN=train --MODEL=mcan_large --DATASET=vqa`
And then it worked

**Comment by Amajo0209** [comment]
Hello! I'm also facing the same. But mine is giving me error

run.py: error: argument --RUN: invalid choice: "'train'" (choose from 'train', 'val', 'test')
