### ISSUE TITLE
What does frcn in the GQA part of Model Zoo stand for?

### ISSUE THREAD

**Issue by ggaemo** [MILVLG/openvqa#54]
![image](https://user-images.githubusercontent.com/8081512/70024032-849b9a80-15dc-11ea-8dc5-96f1474ca703.png)

In the GQA section of the Model zoo, it shows that in every model it incorporates frcn.

What does frcn stand for?

**Comment by ggaemo** [comment]
Does it mean faster-rcnn features..? It seems so...

**Comment by HyperDenton** [comment]
Yes, it is. 'frcn' stands for faster-rcnn features.

**Comment by MIL-VLG** [comment]
yes, frcn feature stands for the Faster RCNN features, which refers to the `Spatial` feature provided by the GQA dataset.
