### ISSUE TITLE
Dataset setup for custom data

### ISSUE THREAD

**Issue by ihabZhaika** [MILVLG/openvqa#60]
Hey,
In the wiki at the Dataset Setup written

> We store the features for each image in a .npz file. You can prepare the visual features by yourself or download the extracted features 

My question is how to train on custom data and to

>  prepare the visual features by yourself

1. So is it the original image converted to numpy format ?
2.  about "each image being represented as an dynamic number (from 10 to 100) of 2048-D", is there a helper function that do this transformation ? and why 10 to 100 ? why 2048D  ?

**Comment by MIL-VLG** [comment]
Hi,
The .npz files are not the original images but extracted region-based features from a pre-trained Faster RCNN model. The feature extraction part please refer to the [bottom-up-attention](https://github.com/yuzcccc/bottom-up-attention) project, and you can use our script to extract the features (see the bottom of the README in the bottom-up-attention project). Please note that **Caffe** is required to run the feature extraction.

**Comment by ihabZhaika** [comment]
> Hi,
> The .npz files are not the original images but extracted region-based features from a pre-trained Faster RCNN model. The feature extraction part please refer to the [bottom-up-attention](https://github.com/yuzcccc/bottom-up-attention) project, and you can use our script to extract the features (see the bottom of the README in the bottom-up-attention project). Please note that **Caffe** is required to run the feature extraction.

Hey,
I saw it, will try and update
