### ISSUE TITLE
Question about the learning rates of butd, ban in gqa dataset.

### ISSUE THREAD

**Issue by lukem209** [MILVLG/openvqa#65]
Hello, from the information in the model zoo for GQA, the learning rates of butd and ban-4 are 2e-4. However,  in the file of configs/gqa/butd and configs/gqa/ban-4. the setting of learning rates is 2e-3. I want to know which learning rate is right for the models (butd, ban-4, ban-8) in the model zoo.
Thank you!

**Comment by ParadoxZW** [comment]
The learning rates in config files are correct. I will fix this bugs in modelzoo file later.

**Comment by lukem209** [comment]
Thank you！
