### ISSUE TITLE
Attention Grounding for GQA

### ISSUE THREAD

**Issue by pkhdipraja** [MILVLG/openvqa#67]
Hello, I am interested in getting the grounding results for GQA but it doesn't seem to be supported at the moment. Is there a plan to support this in the future? or maybe pointer on how to extend the current implementation to support this? (I am particularly interested in getting the result for MCAN model)

Thank you.

**Comment by MIL-VLG** [comment]
If you mean the attention map visualization in the MCAN paper, we currently do not such plan to add this function into openvqa, as we think this is not a generic functionality for other VQA models. Some other 3rdparty repo like [this](https://github.com/shahansa/mcan_attention_visualization) may be helpful for your requirements.

**Comment by pkhdipraja** [comment]
Not for the visualization, but the attention weights are useful for evaluating [grounding](https://cs.stanford.edu/people/dorarad/gqa/evaluate.html) on GQA for attention-based models.

**Comment by MIL-VLG** [comment]
Got it. The additional annotation files for evaluating the grounding performance are not provided for the test set.  Therefore, this result can only be tested online.
