### ISSUE TITLE
How about the result of MCAN model when use frcn_feat + bbox_feat on VQA v2.0 datasets?

### ISSUE THREAD

**Issue by haoopan** [MILVLG/openvqa#69]
Hi , this is great work your team has made, I' m following your work. So how about the result of MCAN model when use frcn_feat + bbox_feat on VQA v2.0 datasets? It's better than only use frcn_feat on VQA v2.0? If not, could you tell me the reason that you think?
Thank you very much:)

**Comment by MIL-VLG** [comment]
Directly apply bbox_feat on MCAN does not have any improvement in our experiments. The reason we are still not very sure. We guess the spatial information should be used in a more elegant way, e.g., the relational self-attention used in our new paper [MMnasNet](https://arxiv.org/pdf/2004.12070.pdf), which has also been implemented in the openvqa project.

**Comment by haoopan** [comment]
I get it, thanks again. I think the reason maybe dataset content, GQA contain many questions about spatial information, but VQA v2.0 dataset doesn't , which caused the result does not have any improvement when concat bbox_feat.
