### ISSUE TITLE
How about the result that MMNasNet model used on GQA dataset?

### ISSUE THREAD

**Issue by haoopan** [MILVLG/openvqa#70]
Hi, I readed MMNasNet paper these days, great work! So I want to know the  result that MMNasNet model used on GQA dataset? Did you have try, has some improvment compare to MCAN model? I'm looking forward your reply, thanks~

**Comment by MIL-VLG** [comment]
The RSA module seems does not have much effect on GQA in my memory. You can run a model yourself to have a try.
