### ISSUE TITLE
Error in Downloading Image Features

### ISSUE THREAD

**Issue by moutaigua8183** [MILVLG/openvqa#71]
I've tried several times, but the error consistantly occurs at the end (like the last 0.05%) of the downloading process for train2014.tar.gz and test2015.tar.gz.    It is fine for val2014.tar.gz.   I suspect that the reason might be the size of the files (that seems the only difference).

I was downloading directly in the Chrome, because I don't know how to use "wget" command for the provided sharable links.
Any solutions?  Thanks!

**Comment by MIL-VLG** [comment]
Sorry that the direct link is not supported : (. 
We have provided the download at Onedrive and BaiduYun. If you come from China, you may try BaiduYun, it should be faster and stable.
