### ISSUE TITLE
Any way to use the original images

### ISSUE THREAD

**Issue by Dhruv-Sabharwal** [MILVLG/openvqa#76]
Hi,
I was implementing some models to do VQA and found your repo really useful. However, it seems like I can only get the FRCN_FEAT and BBOX_FEAT as image inputs to the model. Is there any way to take the original images as inputs and not the extracted features?

**Comment by MIL-VLG** [comment]
It is not that easy and needs plenty of modifications. Currently we do not have such plan to support this.
